### ISSUE TITLE
Personal Profile Opting Out

### ISSUE THREAD

**Issue by LizThompson93** [odota/web#2883] opened 2021-12-24 21:56 UTC
**Is your feature request related to a problem? Please describe.**

I would like to opt-out my profile from OpenDota. I have an issue when players find my OpenDota profile and data and start harassing me because of my stats.

**Describe the solution you'd like**

A simple opt-out option. 

![image](https://user-images.githubusercontent.com/96261305/147372888-7b3c427a-69d7-4407-b7c0-dd23f695caee.png)

1. Remove from public player list.
2. Any profile references displays back to ANONYMOUS. Peers tab/chat history tab/etc.

![image](https://user-images.githubusercontent.com/96261305/147372957-c48ba013-ec90-4296-87ad-63ffefed997d.png)

**Describe alternatives you've considered**

Keep the match data if it breaks the platform but I would like my profile hidden and any reference back to anonymous.

**Comment by Tokumei-Mienai** [comment] 2022-01-05 06:08
I have the same issue and do not understand why OpenDota and Howard is so stubborn in refusing to let players delete their own profile data (profile information and the aggregated player data within it). Clearly illegal in EU. I'm speaking with Valve at the moment to hear their thoughts.

![image](https://user-images.githubusercontent.com/97148285/148167841-9842a057-c8a6-4458-b949-0cd494b5ca3e.png)

**Comment by archcorsair** [comment] 2022-01-07 08:32
@LizThompson93 
This is something you need to do from the Dota client, if you go into Settings then Social, uncheck `Expose Public Match Data` and OpenDota can no longer see your data.
![image](https://user-images.githubusercontent.com/1036921/148515410-fb6e61eb-148a-4447-83c3-ae7c6e1ea551.png)

**Comment by LizThompson93** [comment] 2022-01-23 18:55
> @LizThompson93 This is something you need to do from the Dota client, if you go into Settings then Social, uncheck `Expose Public Match Data` and OpenDota can no longer see your data. ![image](https://user-images.githubusercontent.com/1036921/148515410-fb6e61eb-148a-4447-83c3-ae7c6e1ea551.png)

Hi, okay I did that. How come I see my profile still on OpenDota?

**Comment by archcorsair** [comment] 2022-01-23 20:11
This will not remove historical data but going forward it will not update with new data.

**Comment by LizThompson93** [comment] 2022-01-31 01:31
> This will not remove historical data but going forward it will not update with new data.

That's what I was afraid of. Why isn't this an option?

**Comment by archcorsair** [comment] 2022-01-31 01:43
> That's what I was afraid of. Why isn't opting out your own profile an option?

My understanding is that this information is exposed by Valve itself on the API; OpenDota isn't doing any storing, just reading data that is publicly made available by the Dota API

**Comment by howardchung** [comment] 2023-12-22 23:29
Closing as duplicate of odota/core#2645

**Closed by howardchung** 2023-12-22 23:29 UTC
