### ISSUE TITLE
Void spirit missing from damage given in the Combat tab.

### ISSUE THREAD

**Issue by holmstromjesper** [odota/web#2323] opened 2019-12-11 11:17 UTC
**Current Behavior**
Damage done to void spirit is missing.
In a match, in the "combat tab", void spirit is not shown to take any damage. 
The sum doesn't add up because of this.
[Game 1](https://www.opendota.com/matches/5150200868/combat) missing totally. Console log from this page.
[Game 2](https://www.opendota.com/matches/5148496894/combat) , missing totally on some heroes, some have damage given but no icon.

**Expected behavior/code**
Damage given to void spirit should show, also icon should show.
Total damage for one spell should = all the heroes it have damaged.
**Console Output**

```
----------------------------------SHORT LOG-----------------------------------------------
a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 GET https://api.opendota.com/apps/dota2/images/abilities/kunkka_torrent_storm_sm.png 404

5a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 GET https://api.opendota.com/apps/dota2/images/abilities/kunkka_torrent_storm_sm.png 404

void_spirit_icon.png:1 GET https://api.opendota.com/apps/dota2/images/heroes/void_spirit_icon.png 404


----------------------------------LONG LOG-----------------------------------------------
a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 Fetch finished loading: GET "https://api.opendota.com/api/metadata?".
t @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
925 @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
l @ combat:1
535 @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
l @ combat:1
c @ combat:1
n @ combat:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 Fetch finished loading: GET "https://api.opendota.com/api/matches/5150200868?".
t @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
getMatch @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
value @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Hl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ul @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Zl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
render @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
925 @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
l @ combat:1
535 @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
l @ combat:1
c @ combat:1
n @ combat:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 GET https://api.opendota.com/apps/dota2/images/abilities/kunkka_torrent_storm_sm.png 404
n.setTableRef @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
enqueueSetState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
x.setState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
requestAnimationFrame (async)
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
requestAnimationFrame (async)
value @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
sl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
notify @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.notifyNestedSubs @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.handleChangeWrapper @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
g @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
dispatch @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Promise.then (async)
t @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
getMatch @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
value @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Hl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ul @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Zl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
render @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
925 @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
l @ combat:1
535 @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
l @ combat:1
c @ combat:1
n @ combat:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
api.opendota.com/apps/dota2/images/heroes/void_spirit_icon.png:1 GET https://api.opendota.com/apps/dota2/images/heroes/void_spirit_icon.png 404
Image (async)
xe @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
yl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
bl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ml @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
enqueueSetState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
x.setState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
requestAnimationFrame (async)
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
requestAnimationFrame (async)
value @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
sl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
notify @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.notifyNestedSubs @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.handleChangeWrapper @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
g @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
dispatch @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Promise.then (async)
t @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
getMatch @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
value @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Hl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ul @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Zl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
render @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
925 @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
l @ combat:1
535 @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
l @ combat:1
c @ combat:1
n @ combat:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 GET https://api.opendota.com/apps/dota2/images/abilities/kunkka_torrent_storm_sm.png 404
wt @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Tn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
wn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
load (async)
xn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
yl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
bl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ml @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
enqueueSetState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
x.setState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 GET https://api.opendota.com/apps/dota2/images/abilities/kunkka_torrent_storm_sm.png 404
wt @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Tn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
wn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
load (async)
xn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
yl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
bl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ml @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
enqueueSetState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
x.setState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 GET https://api.opendota.com/apps/dota2/images/abilities/kunkka_torrent_storm_sm.png 404
wt @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Tn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
wn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
load (async)
xn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
yl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
bl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ml @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
enqueueSetState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
x.setState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 GET https://api.opendota.com/apps/dota2/images/abilities/kunkka_torrent_storm_sm.png 404
wt @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Tn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
wn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
load (async)
xn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
yl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
bl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ml @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
enqueueSetState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
x.setState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 GET https://api.opendota.com/apps/dota2/images/abilities/kunkka_torrent_storm_sm.png 404
wt @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Tn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
wn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
load (async)
xn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vn @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
yl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
bl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ml @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
enqueueSetState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
x.setState @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1 Fetch finished loading: GET "https://api.github.com/search/issues?q=repo%3Aodota%2Fweb%20type%3Apr%20base%3Aproduction%20label%3Arelease%20merged%3A%3E2019-12-06&order=desc&page=1&per_page=1".
t @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
getPulls @ index.jsx:180
value @ index.jsx:141
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
vl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
el @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
hi @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Promise.then (async)
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ts @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
wl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
kl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
rl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
t.unstable_runWithPriority @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Wr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Ur @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Gr @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
ul @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
Zl @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
render @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
925 @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
l @ combat:1
535 @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
l @ combat:1
c @ combat:1
n @ combat:1
(anonymous) @ a8585669af8dce9c4b2cb74f43c6870d9ecdc07c.js:1
```

**Environment**
- Browser Version: [Version 78.0.3904.108 (Official Build) (64-bit)]
- OS: [Win 10 edu, Version1903,  OS Build 18362.476]

**Possible Solution**

https://api.opendota.com/apps/dota2/images/heroes/void_spirit_icon.png doens't exist. Check path.
**Additional context/Screenshots**
![chrome_IMcCbZIXG8](https://user-images.githubusercontent.com/35521170/70616836-a36ae400-1c0f-11ea-834b-96bbc1839504.png)

**Comment by howardchung** [comment] 2019-12-11 23:32
I think this is due to needing to update the parser's copy of the heroes file. I've done that, try reparsing this match in 30 minutes or so and see if it fixes.

**Comment by holmstromjesper** [comment] 2019-12-12 08:50
I just re-parsed, didn't solve it :(

**Comment by howardchung** [comment] 2019-12-12 08:57
Oh, I see what the problem is. It's related to the hero icons for the new heroes being missing, so this div is rendering with no width so it's not showing up. Let me see if I can fix those icons.

**Comment by howardchung** [comment] 2019-12-12 09:18
OK, it should be fixed in a few minutes once the new build is deployed.

**Closed** 2019-12-27 06:46 UTC
