### ISSUE TITLE
Battle pass Ti10 Predictions not working, it just shows nothing

### ISSUE THREAD

**Issue by iSton3r** [odota/web#2593] opened 2020-06-02 18:16 UTC
**Current Behavior**
A clear and concise description of the behavior.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by iSton3r** [comment] 2020-06-02 18:17
Battle pass Ti10 Predictions not working, it just shows nothing.
After putting all heroes when we Click on Submit. It shows nothing. Thanks to this we were able to oredcit matched and had streak..I gues that streak is going to Break :(

**Comment by juncombo** [comment] 2020-06-02 19:23
Current Behavior:
I just check and Battle Pass Ti10 Predictions Still not working. When I select the heroes and then hit search it shows zero result.
Expected Behavior:
It should show results that which match it is .
Console Output:
Here is screen shot of console
![Screenshot_1](https://user-images.githubusercontent.com/31518503/83560877-56b5f500-a530-11ea-9b0a-a9452ac488ca.png)

**Comment by howardchung** [comment] 2020-06-02 20:36
Duplicate of https://github.com/odota/web/issues/2591

**Closed by howardchung** 2020-06-02 20:36 UTC
